"use strict";
var _a, _b, _c;
Object.defineProperty(exports, "__esModule", { value: true });
exports.GITHUB_WORKSPACE = exports.IS_READ_ONLY = exports.HEAD_FULL_NAME = exports.BASE_FULL_NAME = exports.ISSUE_NUMBER = exports.REPO = exports.OWNER = exports.EVENT = exports.NAME = void 0;
const tslib_1 = require("tslib");
const github = tslib_1.__importStar(require("@actions/github"));
exports.NAME = 'Eslint Changed';
_a = github.context, exports.EVENT = _a.eventName, _b = _a.issue, exports.OWNER = _b.owner, exports.REPO = _b.repo, exports.ISSUE_NUMBER = _b.number, _c = _a.payload, exports.BASE_FULL_NAME = _c.base.repo.full_name, exports.HEAD_FULL_NAME = _c.head.repo.full_name;
exports.IS_READ_ONLY = exports.BASE_FULL_NAME !== exports.HEAD_FULL_NAME;
exports.GITHUB_WORKSPACE = process.env.GITHUB_WORKSPACE;
